version: '3'

services:
  backend:
    build:
    dockerfile: ./beckend/Dockerfile
  expose:
    - 5000
  ports:
    - "5000:5000"
  links:
    - mongo_db:mongo_db
  depends_on:
    - mongo_db
  #restart: always
  volumes:
    - ./backend/flask_app:/usr/src/app
  command: gunocorn -w 1 -b 0.0.0.0:5000 wsgi:app

mongo_db:
  image: mongo:latest
  restart: unless-stopped
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: 
  volumes:
    - ./mongo_db:/data/db
  ports:
    -"27017:27017"

nginx:
  image: nginx:latest
  ports:
    - "8080:8080"
    - "8081:8081"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  depends_on:
    - frontend
    - backend
  restart: "on-failure"
